# Experiment configuration file.
seml:
  executable: benchmark/cistopic/cistopic_experiment_runner.py
  name: Cistopic
  output_dir: benchmark/cistopic/logs
  project_root_dir: /lustre/groups/ml01/code/laura.martens/scatac_poisson_private/ 
  conda_environment: pycisTopic_env
slurm:
  experiments_per_job: 1
  max_simultaneous_jobs: 5
  sbatch_options_template: CPU
  sbatch_options:
     mem: 250G          # memory
     cpus-per-task: 32  # num cores
     time: 3-00:00     # max time, D-HH:MM

###### BEGIN PARAMETER CONFIGURATION ######

fixed: 
  training.path_to_mallet_binary: "/lustre/groups/ml01/code/laura.martens/github_repos/pycisTopic/Mallet-202108/bin/mallet"
  training.n_topics: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
Neurips:
  fixed:
    #data
    data.dataset: "neurips" 
    data.replacement: 
      - !!python/tuple ["-", ":"]
    setup.batch_key: "batch"
    training.save_path: "/lustre/groups/ml01/workspace/laura.martens/atac_poisson_data/benchmark/neurips/cistopic/"

Satpathy:
  fixed:
    #data
    data.dataset: "satpathy" 
    data.replacement: 
      - !!python/tuple ["_", ":"]
      - !!python/tuple ["_", "-"]
    setup.batch_key: "Group"
    training.save_path: "/lustre/groups/ml01/workspace/laura.martens/atac_poisson_data/benchmark/satpathy/cistopic/"

Aerts:
  fixed:
    #data
    data.dataset: "aerts" 
    data.replacement: 
      - !!python/tuple ["-", ":"]
    setup.batch_key: "runName"
    training.save_path: "/lustre/groups/ml01/workspace/laura.martens/atac_poisson_data/benchmark/aerts/cistopic/"

Trapnell:
  fixed:
    #data
    data.dataset: "trapnell" 
    data.replacement: 
      - !!python/tuple ["-", ":"]
    setup.batch_key: "sample_name"
    training.save_path: "/lustre/groups/ml01/workspace/laura.martens/atac_poisson_data/benchmark/trapnell/cistopic/"


      


